#!/bin/bash
set -euo pipefail

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
LINKFLAGS=""
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static"
CGO_ENABLED=0 go build \
    -trimpath \
    -buildvcs=false \
    -ldflags "-buildid= -X main.VERSION=$VERSION $LINKFLAGS -s -w" \
    -o bin/mount-propagation
ln -sf mount-propagation bin/share-mnt
