#!/bin/bash
set -euo pipefail

if [ -n "${VERSION_OVERRIDE:-}" ]; then
    VERSION="${VERSION_OVERRIDE}"
elif [ -n "${RELEASE_VERSION:-}" ]; then
    VERSION="${RELEASE_VERSION}"
else
    DIRTY=""
    if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
        DIRTY="-dirty"
    fi

    COMMIT=$(git rev-parse --short HEAD)
    GIT_TAG=$(git tag -l --contains HEAD | head -n 1)

    if [ -z "${DIRTY}" ] && [ -n "${GIT_TAG}" ]; then
        VERSION="${GIT_TAG}"
    else
        VERSION="${COMMIT}${DIRTY}"
    fi
fi

ARCH="${ARCH:-amd64}"
export ARCH VERSION
